apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
  
  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    isDefault: false
    jsonData:
      timeFieldName: "@timestamp"
      esVersion: 8 
      index: logstash-*
      interval: "15s"
    version: 1