global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /q/metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['api-gateway:8080']
  
  - job_name: 'jaeger'
    metrics_path: /metrics
    static_configs:
      - targets: ['jaeger:14269']

  - job_name: 'elasticsearch'
    metrics_path: /metrics
    static_configs:
      - targets: ['elasticsearch-exporter:9114']